# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Padraignix's InfoSec Blog_
email: padraignix@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog covering CTF events, Security Infrastructure, Cryptography, Emulator development and related adventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://padraignix.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Google Analytics
google_analytics: UA-148947358-1

social_links:
    twitter: Padraignix_
    github:  padraignix
    rss: rss
    linkedin: downingpatrick
    hackerone: padraignix
    
github_username:  padraignix

home:
    url: "/"
    title: "Home"

about:
    url: "/about/"
    title: "About"

archive:
    url: "/archive/"
    title: "Archive"
    
# Build settings
markdown: kramdown
theme: jekyll-theme-time-machine
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock