# Site settings
title: "Padraignix's InfoSec Blog_"
email: padraignix@gmail.com
description: "Personal blog covering CTF events, Security Infrastructure, Cryptography, Emulator development and related adventures"
baseurl: ""
url: "https://padraignix.github.io"
title_description: "Personal blog covering CTF events, HTB writeups, Bug Bounties, Security Infrastructure, Cryptography, Emulator development and related adventures"
title_image: "https://github.com/padraignix.png"
google_analytics: "UA-148947358-1"
disqus_account: 
github_repository: https://github.com/padraignix
addthis_id: ra-5d90e1af4e80d2a2
post_limit: 5

# Social usernames/URLs
twitter_username: Padraignix_
github_username: padraignix
instagram_username: 
reddit_username: 
linkedin_link: http://linkedin.com/in/downingpatrick
google_plus_link: 
stackoverflow_link:
xing_link:
facebook_link:
hackerone_username: padraignix
hackthebox_username: 137488

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_left: <i class="fa fa-copyright"></i> 2019 Padraignix
footer_right: <i class="fa fa-code"></i>Padraignix on <a href="https://github.com/padraignix">Github</a> &nbsp;<i class=\"fa fa-github\"></i>
# Experience is valuable only if it's imbued with meaning from which one can draw salient conclusions. Otherwise, experience becomes imprisoning - Barry McCaffrey

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
